"""empty message

Revision ID: 04ad3359928c
Revises: 6e28f9ae0ab0
Create Date: 2023-07-05 18:05:09.401944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ad3359928c'
down_revision = '6e28f9ae0ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vegan_tag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('vegetarian_tag', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('image_', sa.Integer(), nullable=False))

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_', sa.Integer(), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('image_')

    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.drop_column('image_')
        batch_op.drop_column('vegetarian_tag')
        batch_op.drop_column('vegan_tag')

    # ### end Alembic commands ###
