"""empty message

Revision ID: 6b960c7e4382
Revises: 75e1c9e19c27
Create Date: 2023-07-03 16:58:25.237354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b960c7e4382'
down_revision = '75e1c9e19c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_groups_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('ingredients_group_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'food_groups', ['food_groups_id'], ['id'])
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ingredients_group_id_fkey', 'food_groups', ['group_id'], ['id'])
        batch_op.drop_column('food_groups_id')

    # ### end Alembic commands ###
