"""empty message

Revision ID: d915331b8f34
Revises: a930def01947
Create Date: 2023-07-07 02:58:56.781138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd915331b8f34'
down_revision = 'a930def01947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('image_',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredients', schema=None) as batch_op:
        batch_op.alter_column('image_',
               existing_type=sa.String(length=150),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
